config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  root "static_pages#top"

  namespace :search_crypto_exchanges do
    get :select_purpose
    get :select_coin
    get :select_coin_to_wallet
    post :result
    post :result_to_wallet
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/buying_fee.rb
class BuyingFee < ApplicationRecord
  belongs_to :cryptocurrency_price

  validates :buying_fee, presence: true, numericality: true
end

app/models/crypto_withdrawal_fee.rb
class CryptoWithdrawalFee < ApplicationRecord
  belongs_to :cryptocurrency_price
  belongs_to :network

  validates :minimum_withdrawal, presence: true, numericality: true
  validates :withdrawal_fee, presence: true, numericality: true
end

app/models/cryptocurrency.rb
class Cryptocurrency < ApplicationRecord
  mount_uploader :icon, CryptocurrencyUploader

  has_many :cryptocurrency_prices, dependent: :destroy

  validates :name, presence: true, uniqueness: true
  validates :code, presence: true
end

app/models/cryptocurrency_price.rb
class CryptocurrencyPrice < ApplicationRecord
  belongs_to :cryptocurrency
  belongs_to :exchange

  has_one :buying_fee, dependent: :destroy
  has_many :crypto_withdrawal_fees, dependent: :destroy

  validates :asking_price, numericality: { greater_than_or_equal_to: 0 }
end

app/models/exchange.rb
class Exchange < ApplicationRecord
  has_many :cryptocurrency_prices, dependent: :destroy

  validates :name, presence: true
end

app/models/limit_order.rb
class LimitOrder < ApplicationRecord
  belongs_to :cryptocurrency

  enum purpose: { purchase: 1, purchase_to_wallet: 2 }

  validates :asking_purchase_price, presence: true, numericality: true
  validates :asking_purchase_amount, presence: true, numericality: true
  validates :purpose, presence: true, numericality: { only_integer: true }
  validates :cryptocurrency, presence: true

  # 購入可能量を計算
  # (希望購入金額 / 購入価格) × ( 1 - 購入手数料 ) - 出金手数料 = 購入可能量
  def available_asking_purchase_amounts
    response = []

    cryptocurrency_prices = Cryptocurrency.find_by(id: self.cryptocurrency_id).cryptocurrency_prices
    cryptocurrency_prices.each do |cryptocurrency_price|
      asking_purchase_amount = (self.asking_purchase_price / cryptocurrency_price.asking_price) * (1 - cryptocurrency_price.buying_fee.buying_fee * 0.01)
      exchange = cryptocurrency_price.exchange

      if purchase?
        response.push({ exchange: exchange.name, asking_purchase_amount: asking_purchase_amount })
      else
        cryptocurrency_price.crypto_withdrawal_fees.each do |crypto_withdrawal_fee|
          network = crypto_withdrawal_fee.network.name
          response.push({ exchange: exchange.name, asking_purchase_amount: asking_purchase_amount - crypto_withdrawal_fee.withdrawal_fee, network: network })
        end
      end
    end

    response.sort_by! { |a| a[:asking_purchase_amount] }
  end
end

app/models/network.rb
class Network < ApplicationRecord
  has_many :crypto_withdrawal_fees

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/search_crypto_exchanges_controller.rb
class SearchCryptoExchangesController < ApplicationController
  def select_purpose; end

  def select_coin
    @select_coin_form = SelectCoinForm.new
  end

  def select_coin_to_wallet
    @select_coin_form = SelectCoinForm.new
  end

  def result
    @select_coin_form = SelectCoinForm.new(search_crypto_exchange_params)
    if @select_coin_form.valid?
      limit_order = LimitOrder.new(cryptocurrency_id: search_crypto_exchange_params[:cryptocurrency_id], asking_purchase_price: search_crypto_exchange_params[:asking_purchase_price], purpose: 1)
      @asking_purchase_amounts = limit_order.available_asking_purchase_amounts
      render :result, asking_purchase_amounts: @asking_purchase_amounts
    else
      render :select_coin, status: :unprocessable_entity
    end
  end

  def result_to_wallet
    @select_coin_form = SelectCoinForm.new(search_crypto_exchange_params)
    if @select_coin_form.valid?
      limit_order = LimitOrder.new(cryptocurrency_id: search_crypto_exchange_params[:cryptocurrency_id], asking_purchase_price: search_crypto_exchange_params[:asking_purchase_price], purpose: 2)
      @asking_purchase_amounts = limit_order.available_asking_purchase_amounts
      render :result_to_wallet, asking_purchase_amounts: @asking_purchase_amounts
    else
      render :select_coin, status: :unprocessable_entity
    end
  end

  private

  def search_crypto_exchange_params
    params.require(:select_coin_form).permit(:cryptocurrency_id, :asking_purchase_price)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def top; end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title(title = "")
    base_title = t("defaults.title")
    title.empty? ? base_title : "#{title} | #{base_title}"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= page_title(yield(:title)) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <%= render 'shared/before_login_header' %>
    <%= yield %>
    <%= render 'shared/footer' %>
  </body>
</html>

app/views/search_crypto_exchanges/_form.html.erb
<%= form_with model: select_coin_form, url: url, data: { turbo: false } do |f| %>
  <%= render "shared/error_messages", object: f.object %>
  <div class="form-control w-64 mx-auto">
    <%= f.label :cryptocurrency_id, class: "label label-text" %>
    <%= f.collection_select :cryptocurrency_id, Cryptocurrency.all, :id, :code, {prompt: (t 'helpers.prompt.select_coin_form.cryptocurrency_id')}, {class: "select select-primary w-full max-w-xs"} %>
  </div>
  <div class="form-control w-64 mx-auto py-6">
    <%= f.label :asking_purchase_price, class: "label label-text" %>
    <%= f.number_field :asking_purchase_price, step: "0.00000001", placeholder: (t 'helpers.placeholder.select_coin_form.asking_purchase_price'), class: "input input-primary w-full max-w-xs" %>
  </div>
  <%= f.submit (t 'helpers.submit.result') , class: "btn btn-primary" %>
<% end %>

app/views/search_crypto_exchanges/_row.html.erb
<tr class="<%= 'bg-primary' if row_counter.zero? %>">
  <td><%= row_counter + 1 %></td>
  <td><%= row[:exchange] %></td>
  <td><%= row[:asking_purchase_amount].round(8) %></td>
  <% if row[:network] %>
    <td><%= row[:network] %></td>
  <% end %>
</tr>

app/views/search_crypto_exchanges/_table.html.erb
<div class="overflow-x-auto">
  <table class="table">
    <thead>
      <tr>
        <th></th>
        <th><%= Exchange.model_name.human %></th>
        <th><%= t '.available_asking_purcahse_amount' %></th>
        <% if asking_purchase_amounts[0][:network] %>
          <td><%= Network.model_name.human %></td>
        <% end %>
    </thead>
    <tbody>
      <%= render partial: 'row', collection: @asking_purchase_amounts %>
    </tbody>
  </table>
</div>

app/views/search_crypto_exchanges/result.html.erb
<%= content_for(:title, t('.title')) %>

<div class="hero bg-base-200 text-base-content p-10">
  <div class="hero-content text-center">
    <div class="max-w-md">
      <h1 class="text-5xl font-bold"><%= t '.title' %></h1>
      <div class="py-6">
        <%= render "table", asking_purchase_amounts: @asking_purchase_amounts %>
      </div>
    </div>
  </div>
</div>

app/views/search_crypto_exchanges/result_to_wallet.html.erb
<%= content_for(:title, t('.title').gsub("<br />", "")) %>

<div class="hero bg-base-200 text-base-content p-10">
  <div class="hero-content text-center">
    <div class="max-w-md">
      <h1 class="text-5xl font-bold"><%= (t '.title').html_safe %></h1>
      <div class="py-6">
        <%= render "table", asking_purchase_amounts: @asking_purchase_amounts %>
      </div>
    </div>
  </div>
</div>

app/views/search_crypto_exchanges/select_coin.html.erb
<%= content_for(:title, t('.title')) %>

<div class="hero bg-base-200 text-base-content p-10">
  <div class="hero-content text-center">
    <div class="max-w-md">
      <h1 class="text-5xl font-bold"><%= t '.title' %></h1>
      <div class="py-6">
        <%= render "form", select_coin: @select_coin, url: search_crypto_exchanges_result_path %>
      </div>
    </div>
  </div>
</div>

app/views/search_crypto_exchanges/select_coin_to_wallet.html.erb
<%= content_for(:title, t('.title').gsub("<br />", "")) %>

<div class="hero bg-base-200 text-base-content p-10">
  <div class="hero-content text-center">
    <div class="max-w-md">
      <h1 class="text-5xl font-bold"><%= (t '.title').html_safe %></h1>
      <div class="py-6">
        <%= render "form", select_coin: @select_coin_to_wallet, url: search_crypto_exchanges_result_to_wallet_path %>
      </div>
    </div>
  </div>
</div>

app/views/search_crypto_exchanges/select_purpose.html.erb
<%= content_for(:title, t('.title')) %>

<div class="hero bg-base-200 text-base-content p-10">
  <div class="hero-content text-center">
    <div class="max-w-md">
      <h1 class="text-5xl font-bold"><%= t '.title' %></h1>
      <div class="py-6">
        <%= link_to (t '.search_exchange'), search_crypto_exchanges_select_coin_path, class:"btn btn-primary my-6 before:content-['🔰']" %><br>
        <%= link_to (t '.search_exchange_to_wallet').html_safe, search_crypto_exchanges_select_coin_to_wallet_path, class:"btn btn-primary" %>
      </div>
    </div>
  </div>
</div>

app/views/shared/_before_login_header.html.erb
<header class="bg-primary text-base-content p-10">
  <nav class="flex justify-between w-full">
    <%= link_to ( t "header.top"), root_path, class:"link link-hover text-left" %>
    <div class="flex gap-4">
      <%= link_to ( t "header.search_exchange"), search_crypto_exchanges_select_purpose_path, class:"link link-hover text-end" %>
    </div>
  </nav>
</header>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div role="alert" class="alert alert-error mb-3">
    <div class="mb-0">
      <% object.errors.each do |error| %>
        <div class="flex py-1">
          <svg
            xmlns="http://www.w3.org/2000/svg"
            class="h-6 w-6 shrink-0 stroke-current"
            fill="none"
            viewBox="0 0 24 24">
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              stroke-width="2"
              d="M10 14l2-2m0 0l2-2m-2 2l-2-2m2 2l2 2m7-2a9 9 0 11-18 0 9 9 0 0118 0z" />
          </svg>
          <span><%= error.full_message %></span>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class="footer footer-center bg-secondary text-base-content p-10">
  <nav class="flex justify-between w-full">
    <%= link_to ( t "footer.contact" ), "#", class:"link link-hover text-left" %>
    <div class="flex gap-4">
      <%= link_to ( t "footer.terms_of_service" ), "#", class:"link link-hover text-end" %>
      <%= link_to ( t "footer.privacy_policy" ), "#", class:"link link-hover text-end" %>
    </div>
  </nav>
  <aside>
    <p>Copyright © 2024 - All right reserved by Takehiro Sato</p>
  </aside>
</footer>

app/views/static_pages/top.html.erb
<div class="hero bg-base-200 text-base-content p-10">
  <div class="hero-content text-center">
    <div class="max-w-md">
      <h1 class="text-5xl font-bold">トップページ</h1>
      <p class="py-6">本アプリの使い方を記載。本アプリの使い方を記載。本アプリの使い方を記載。本アプリの使い方を記載。本アプリの使い方を記載。本アプリの使い方を記載。</p>
      <div class="flex justify-around items-center">
        <%= link_to image_tag("btn_login_base.png"), "#" %>
        <%= link_to (t '.search_exchange'), search_crypto_exchanges_select_purpose_path, class:"btn btn-primary" %>
      </div>
    </div>
  </div>
</div>